function results = plot_anatomy_supplements( ...
    muscimolFile, photometryFile, opInTaskFile, ...
    opOutOfTaskFile, optoBehaviorFile, templateFile, outputFolder)
%PLOT_ANATOMY_SUPPLEMENTS Reproduce the Allen-atlas targeting panels.
%
% results = plot_anatomy_supplements( ...
%     muscimolFile, photometryFile, opInTaskFile, ...
%     opOutOfTaskFile, optoBehaviorFile, templateFile, outputFolder)
%
% Reproduces the coordinate-based anatomy panels in Figures S1, S3, S8,
% S10, and S12. Each panel is exported separately because histology images,
% schematics, and final panel labels were added during manuscript layout.
%
% Inputs
% ------
% muscimolFile      : animalsMuscimol.csv
% photometryFile    : animalsPhotometry.csv
% opInTaskFile      : animalsOPInTask.csv
% opOutOfTaskFile   : animalsOPOutOfTask.csv
% optoBehaviorFile  : animalsOptoBehavior.csv
% templateFile      : local Allen CCFv3 average_template_10.nrrd
% outputFolder      : destination for panel figures and coordinate tables
%
% Output
% ------
% results is a nested structure organized by manuscript figure and panel.
% Every leaf contains the figure handle, plotted site table, and animal
% summary returned by plot_allen_coronal_sections.

narginchk(7,7);

muscimolFile = requireFile(muscimolFile,"Muscimol animal table");
photometryFile = requireFile(photometryFile,"Photometry animal table");
opInTaskFile = requireFile(opInTaskFile,"In-task opto-photometry animal table");
opOutOfTaskFile = requireFile(opOutOfTaskFile,"Out-of-task opto-photometry animal table");
optoBehaviorFile = requireFile(optoBehaviorFile,"Optogenetic inhibition animal table");
templateFile = requireFile(templateFile,"Allen average template");

outputFolder = string(outputFolder);
assert(isscalar(outputFolder) && strlength(outputFolder)>0, ...
    'outputFolder must be a nonempty path.');
if ~isfolder(outputFolder)
    mkdir(outputFolder);
end

assert(exist('nrrdread','file')==2, ...
    ['nrrdread is not available. Install MATLAB Medical Imaging Toolbox ' ...
     'or place a compatible nrrdread implementation on the MATLAB path.']);

fprintf('Reading anatomy metadata tables...\n');
muscimol = readtable(muscimolFile,'TextType','string');
photometry = readtable(photometryFile,'TextType','string');
opInTask = readtable(opInTaskFile,'TextType','string');
opOutOfTask = readtable(opOutOfTaskFile,'TextType','string');
optoBehavior = readtable(optoBehaviorFile,'TextType','string');

results = struct();

%% Figure S1: muscimol targeting

results.figureS1.panelA = renderPanel( ...
    muscimol, templateFile, outputFolder, ...
    "figureS1_panelA_muscimol_targeting", ...
    "mDMS muscimol targeting", ...
    'ShowAnimals',"included");

%% Figure S3: interneuron photometry targeting in mDMS

requireVariables(photometry,["photo_cell","site", ...
    "usable_data_left","usable_data_right"],"Photometry animal table");

cellTypes = ["pv","ltsi","thin"];
resultFields = ["panelC","panelD","panelE"];
outputNames = [ ...
    "figureS3_panelC_pv_targeting", ...
    "figureS3_panelD_sst_targeting", ...
    "figureS3_panelE_th_targeting"];
figureTitles = [ ...
    "PV interneuron photometry targeting", ...
    "SST interneuron photometry targeting", ...
    "TH interneuron photometry targeting"];

for i = 1:numel(cellTypes)
    use = textEquals(photometry.photo_cell,cellTypes(i)) & ...
        textEquals(photometry.site,"mdms");
    assert(any(use),'No mDMS %s photometry animals were found.',cellTypes(i));
    results.figureS3.(char(resultFields(i))) = renderPanel( ...
        photometry(use,:), templateFile, outputFolder, ...
        outputNames(i), figureTitles(i), ...
        'LeftInclusionVariable',"usable_data_left", ...
        'RightInclusionVariable',"usable_data_right", ...
        'ShowAnimals',"all");
end

%% Figure S8: SPN photometry targeting in mDMS

cellTypes = ["d1","a2a"];
resultFields = ["panelB","panelD"];
outputNames = [ ...
    "figureS8_panelB_d1_targeting", ...
    "figureS8_panelD_a2a_targeting"];
figureTitles = [ ...
    "D1-SPN photometry targeting", ...
    "A2A-SPN photometry targeting"];

for i = 1:numel(cellTypes)
    use = textEquals(photometry.photo_cell,cellTypes(i)) & ...
        textEquals(photometry.site,"mdms");
    assert(any(use),'No mDMS %s photometry animals were found.',cellTypes(i));
    results.figureS8.(char(resultFields(i))) = renderPanel( ...
        photometry(use,:), templateFile, outputFolder, ...
        outputNames(i), figureTitles(i), ...
        'LeftInclusionVariable',"usable_data_left", ...
        'RightInclusionVariable',"usable_data_right", ...
        'ShowAnimals',"all");
end

%% Figure S10: TH excitation with simultaneous photometry

requireVariables(opInTask,["photo_cell","opto_cell","opsin", ...
    "usable_data_left","usable_data_right"],"In-task TH-SST animal table");
use = textEquals(opInTask.photo_cell,"sst") & ...
    textEquals(opInTask.opto_cell,"th") & ...
    textEquals(opInTask.opsin,"chrimson");
assert(any(use),'No in-task TH-Chrimson/SST-photometry animals were found.');
results.figureS10.panelC = renderPanel( ...
    opInTask(use,:), templateFile, outputFolder, ...
    "figureS10_panelC_sst_in_task_targeting", ...
    "TH excitation with SST photometry: in task", ...
    'LeftInclusionVariable',"usable_data_left", ...
    'RightInclusionVariable',"usable_data_right", ...
    'ShowAnimals',"all");

requireVariables(opOutOfTask,["photo_cell","opto_cell","opsin", ...
    "usable_data_left","usable_data_right"], ...
    "Out-of-task opto-photometry animal table");
photoCells = ["sst","d1","a2a"];
resultFields = ["panelB","panelE","panelG"];
outputNames = [ ...
    "figureS10_panelB_sst_out_of_task_targeting", ...
    "figureS10_panelE_d1_out_of_task_targeting", ...
    "figureS10_panelG_a2a_out_of_task_targeting"];
figureTitles = [ ...
    "TH excitation with SST photometry: out of task", ...
    "TH excitation with D1-SPN photometry: out of task", ...
    "TH excitation with A2A-SPN photometry: out of task"];

for i = 1:numel(photoCells)
    use = textEquals(opOutOfTask.photo_cell,photoCells(i)) & ...
        textEquals(opOutOfTask.opto_cell,"th") & ...
        textEquals(opOutOfTask.opsin,"chrimson");
    assert(any(use), ...
        'No out-of-task TH-Chrimson/%s-photometry animals were found.', ...
        photoCells(i));
    results.figureS10.(char(resultFields(i))) = renderPanel( ...
        opOutOfTask(use,:), templateFile, outputFolder, ...
        outputNames(i), figureTitles(i), ...
        'LeftInclusionVariable',"usable_data_left", ...
        'RightInclusionVariable',"usable_data_right", ...
        'ShowAnimals',"all");
end

%% Figure S12: repeated SST and TH inhibition cohorts

requireVariables(optoBehavior,["animal_id","cell_type","condition", ...
    "behavior_incl","slice_incl"],"Optogenetic inhibition animal table");
optoBehavior.animalID = optoBehavior.animal_id;
includedExperiment = textEquals(optoBehavior.behavior_incl,"y") | ...
    textEquals(optoBehavior.slice_incl,"y");

cellTypes = ["sst","sst","th","th"];
conditions = ["ctrl","ib","ctrl","ib"];
resultFields = ["sstControl","sstInhibition","thControl","thInhibition"];
outputNames = [ ...
    "figureS12_panelC_sst_control_targeting", ...
    "figureS12_panelC_sst_inhibition_targeting", ...
    "figureS12_panelD_th_control_targeting", ...
    "figureS12_panelD_th_inhibition_targeting"];
figureTitles = [ ...
    "SST control targeting", ...
    "SST inhibition targeting", ...
    "TH control targeting", ...
    "TH inhibition targeting"];

for i = 1:numel(cellTypes)
    use = includedExperiment & ...
        textEquals(optoBehavior.cell_type,cellTypes(i)) & ...
        textEquals(optoBehavior.condition,conditions(i));
    assert(any(use),'No %s/%s optogenetic animals were found.', ...
        cellTypes(i),conditions(i));
    results.figureS12.(char(resultFields(i))) = renderPanel( ...
        optoBehavior(use,:), templateFile, outputFolder, ...
        outputNames(i), figureTitles(i), ...
        'ShowAnimals',"all");
end

results.inputFiles = struct( ...
    'muscimol',muscimolFile, ...
    'photometry',photometryFile, ...
    'opInTask',opInTaskFile, ...
    'opOutOfTask',opOutOfTaskFile, ...
    'optoBehavior',optoBehaviorFile, ...
    'allenTemplate',templateFile);
results.outputFolder = outputFolder;

fprintf('Finished anatomy panels. Outputs: %s\n',outputFolder);

end


function result = renderPanel(T,templateFile,outputFolder, ...
    outputName,figureTitle,varargin)

outputStem = fullfile(outputFolder,outputName);
[fig,sites,animalSummary] = plot_allen_coronal_sections( ...
    T, templateFile, ...
    'OutputStem',outputStem, ...
    'FigureTitle',figureTitle, ...
    varargin{:});

writetable(sites,outputStem+"_sites.csv");
writetable(animalSummary,outputStem+"_animals.csv");

result = struct( ...
    'figure',fig, ...
    'sites',sites, ...
    'animals',animalSummary, ...
    'outputStem',outputStem);

end


function file = requireFile(file,label)
file = string(file);
assert(isscalar(file) && strlength(file)>0, ...
    '%s path must be a nonempty text scalar.',label);
assert(isfile(file),'%s not found: %s',label,file);
end


function requireVariables(T,variables,label)
missing = setdiff(variables,string(T.Properties.VariableNames));
assert(isempty(missing),'%s is missing required variable(s): %s', ...
    label,strjoin(missing,', '));
end


function tf = textEquals(values,target)
tf = lower(strtrim(string(values))) == lower(string(target));
tf(ismissing(tf)) = false;
end
