function results = plot_rlhmm_figureS15( ...
        masterLLFile, posteriorFile, animalFile, outputFolder)
%PLOT_RLHMM_FIGURES15 Reproduce analytical panels C-L of Figure S15.
%
% RESULTS = PLOT_RLHMM_FIGURES15(MASTERLLFILE, POSTERIORFILE,
% ANIMALFILE, OUTPUTFOLDER) produces the model-comparison, example-session,
% state-duration, states-per-session, and empirical-transition panels from
% the submitted supplemental figure.
%
% Required inputs
% ---------------
% MASTERLLFILE
%   Consolidated held-out model-evaluation table with one row per
%   animal x model and columns animalID, model, and testLL_perTrial.
% POSTERIORFILE
%   rlhmm_posteriors.csv from the selected three-state fit. Required
%   columns are animalID, iOrig, jOrig, stateProb_1, stateProb_2,
%   stateProb_3, and stateMAP.
% ANIMALFILE
%   Animal roster containing animal_id and sex.
% OUTPUTFOLDER
%   Optional. When supplied, figures are exported as PNG and PDF and
%   source-data/statistics tables are written as CSV files.
%
% Figure scope
% ------------
% Panels A and B are conceptual schematics assembled as artwork and are
% therefore not generated by this analysis function. This function creates:
%   C     held-out model comparison relative to QF;
%   D-I   six explicitly selected posterior-probability examples;
%   J     mean hard-MAP state-run duration by animal;
%   K     percentage of sessions containing 1, 2, or 3 hard-MAP states;
%   L     empirical off-diagonal hard-MAP transition probabilities.
%
% Historical-reproduction decisions
% -----------------------------------
% 1. Panel C plots each model relative to QF but applies paired Wilcoxon
%    signed-rank tests incrementally between adjacent models.
%    It uses the precomputed testLL_perTrial values in masterLL. The legacy
%    fixed-value GLMs omit two history-initialization trials per session;
%    this function preserves the submitted scoring rather than rescoring.
% 2. Panels D-I use the six sessions manually selected for the submitted
%    figure. They are pinned by animalID and iOrig; no random selection is
%    performed.
% 3. Panels J-L use hard maximum-a-posteriori state assignments (stateMAP),
%    matching the legacy analysis.
% 4. Panel J first averages run duration within animal x state, then takes
%    the population mean across animals.
% 5. Panel K first calculates session-category percentages within animal,
%    then takes the population mean across animals.
% 6. Panel L removes self-transitions from empirical transition counts and
%    row-normalizes the remaining counts. It is not the fitted HMM
%    transition matrix.
%
% Software
% --------
% MATLAB's Statistics and Machine Learning Toolbox is required for BOXPLOT
% and SIGNRANK. No Python environment or upstream GLM-HMM repository is
% required once the input CSV files have been generated.

    if nargin < 4
        outputFolder = '';
    end

    inputFiles = {masterLLFile, posteriorFile, animalFile};
    for iFile = 1:numel(inputFiles)
        if ~isfile(inputFiles{iFile})
            error('Input file does not exist: %s', inputFiles{iFile});
        end
    end

    if ~isempty(outputFolder) && ~isfolder(outputFolder)
        mkdir(outputFolder);
    end

    colors = [ ...
        75 105 177; ...    % State 1: #4b69b1
        60 192 196; ...    % State 2: #3cc0c4
        153 57 149] ./ 255; % State 3: #993995
    states = (1:3)';

    %% Read and validate inputs
    M = readtable(masterLLFile, 'TextType', 'string');
    T = readtable(posteriorFile, 'TextType', 'string');
    animals = readtable(animalFile, 'TextType', 'string');

    requireVariables(M, {'animalID','model','testLL_perTrial'}, ...
        'master LL table');
    requireVariables(T, {'animalID','iOrig','jOrig', ...
        'stateProb_1','stateProb_2','stateProb_3','stateMAP'}, ...
        'posterior table');
    requireVariables(animals, {'animal_id','sex'}, 'animal roster');

    assertUniqueRows(M, {'animalID','model'}, 'master LL table');
    assertUniqueRows(T, {'animalID','iOrig','jOrig'}, 'posterior table');

    M.model = string(M.model);
    T = sortrows(T, {'animalID','iOrig','jOrig'});

    if any(~isfinite(M.testLL_perTrial))
        error('master LL table contains non-finite testLL_perTrial values.');
    end

    probabilityVars = {'stateProb_1','stateProb_2','stateProb_3'};
    posteriorSum = sum(T{:, probabilityVars}, 2);
    if any(~isfinite(posteriorSum)) || any(abs(posteriorSum - 1) > 1e-8)
        error('Posterior state probabilities must be finite and sum to one.');
    end
    if any(~ismember(T.stateMAP, states))
        error('stateMAP contains values outside States 1-3.');
    end

    nSessions = height(unique(T(:, {'animalID','iOrig'}), 'rows'));
    fprintf('Validated %d posterior trials, %d sessions, and %d animals.\n', ...
        height(T), nSessions, numel(unique(T.animalID)));

    %% Panel C: held-out model comparison
    [figC, modelStats, modelPlotData] = plotPanelC(M, animals);

    %% Panels D-I: pinned example sessions
    exampleSessions = table( ...
        (1:6)', ...
        [456; 457; 471; 467; 473; 440], ...
        [12; 31; 38; 13; 21; 5], ...
        [162; 167; 148; 154; 150; 164], ...
        'VariableNames', {'example','animalID','iOrig','expected_trials'});

    [figExamples, exampleSessions] = plotExampleSessions( ...
        T, exampleSessions, colors);

    %% Panel J: animal-level mean hard-MAP run duration
    [meanDuration, durationByAnimal] = calculateStateDurations(T, states);
    figJ = plotStateDuration(durationByAnimal, meanDuration, colors);

    durationStats = compareStatesToOne( ...
        durationByAnimal{:, compose('state_%d', states)}, ...
        states, [2 1; 3 1], 'median_delta_trials');

    %% Panel K: number of hard-MAP states represented per session
    [sessionStateCounts, stateCountByAnimal] = ...
        calculateStatesPerSession(T, states);
    meanSessionPct = mean( ...
        stateCountByAnimal{:, compose('pct_%d_states', states)}, ...
        1, 'omitnan');
    figK = plotStatesPerSession(stateCountByAnimal, meanSessionPct);

    %% Panel L: off-diagonal empirical hard-MAP transitions
    [transitionCounts, transitionProbabilities] = ...
        calculateEmpiricalTransitions(T, states);
    figL = plotEmpiricalTransitions(transitionProbabilities);

    %% Collect results
    results = struct;
    results.model_comparison_values = modelPlotData;
    results.model_comparison_stats = modelStats;
    results.example_sessions = exampleSessions;
    results.state_duration_by_animal = durationByAnimal;
    results.state_duration_means = array2table(meanDuration, ...
        'VariableNames', compose('state_%d', states));
    results.state_duration_stats = durationStats;
    results.session_state_counts = sessionStateCounts;
    results.states_per_session_by_animal = stateCountByAnimal;
    results.transition_counts = matrixToStateTable(transitionCounts, states);
    results.transition_probabilities = ...
        matrixToStateTable(transitionProbabilities, states);

    fprintf('\nPanel J population means (trials): %.3f, %.3f, %.3f\n', ...
        meanDuration);
    fprintf('Panel K population means (%% sessions): %.3f, %.3f, %.3f\n', ...
        meanSessionPct);
    fprintf('Panel L off-diagonal row-normalized transition matrix:\n');
    disp(transitionProbabilities);

    %% Optional export
    if ~isempty(outputFolder)
        saveFigurePair(figC, outputFolder, 'panelC_model_comparison');
        saveFigurePair(figExamples, outputFolder, ...
            'panelsD_to_I_example_sessions');
        saveFigurePair(figJ, outputFolder, 'panelJ_state_duration');
        saveFigurePair(figK, outputFolder, 'panelK_states_per_session');
        saveFigurePair(figL, outputFolder, ...
            'panelL_empirical_transitions');

        writeResultTable(modelPlotData, outputFolder, ...
            'panelC_model_comparison_values.csv');
        writeResultTable(modelStats, outputFolder, ...
            'panelC_incremental_signrank.csv');
        writeResultTable(exampleSessions, outputFolder, ...
            'panelsD_to_I_example_sessions.csv');
        writeResultTable(durationByAnimal, outputFolder, ...
            'panelJ_state_duration_by_animal.csv');
        writeResultTable(durationStats, outputFolder, ...
            'panelJ_state_duration_stats.csv');
        writeResultTable(sessionStateCounts, outputFolder, ...
            'panelK_session_state_counts.csv');
        writeResultTable(stateCountByAnimal, outputFolder, ...
            'panelK_states_per_session_by_animal.csv');
        writeResultTable(results.transition_counts, outputFolder, ...
            'panelL_transition_counts.csv');
        writeResultTable(results.transition_probabilities, outputFolder, ...
            'panelL_transition_probabilities.csv');
    end
end


function [fig, statsTable, plotData] = plotPanelC(T, animals)
    modelVars = [
        "M5_value_bias_WSLS_choiceHx_switchiness"
        "M6_splitValue_bias_WSLS_choiceHx_switchiness"
        "M6_online_splitValue_bias_WSLS_choiceHx_switchiness"
        "RLHMM_K2_stateAlpha_splitBeta_hybrid"
        "RLHMM_K3_stateAlpha_splitBeta_hybrid"
    ];
    modelLabels = [
        "GLM (single \DeltaQ)"
        "GLM (split \DeltaQ)"
        "RL-GLM"
        "RL-GLM-HMM (2-state)"
        "RL-GLM-HMM (3-state)"
    ];
    requiredModels = ["QF"; modelVars];

    missingModels = setdiff(requiredModels, unique(T.model));
    if ~isempty(missingModels)
        error('master LL table missing required model(s): %s', ...
            strjoin(missingModels, ', '));
    end

    T = T(ismember(T.model, requiredModels), ...
        {'animalID','model','testLL_perTrial'});
    W = unstack(T, 'testLL_perTrial', 'model');
    requireVariables(W, cellstr(requiredModels), ...
        'wide model-comparison table');

    if any(~isfinite(W{:, cellstr(requiredModels)}), 'all')
        error('At least one animal lacks a required model score.');
    end

    animalSex = animals(:, {'animal_id','sex'});
    animalSex = renamevars(animalSex, 'animal_id', 'animalID');
    animalSex.sex = lower(strtrim(string(animalSex.sex)));
    animalSex = unique(animalSex, 'rows', 'stable');
    assertUniqueRows(animalSex, {'animalID'}, 'animal-to-sex mapping');

    plotData = table;
    for iModel = 1:numel(modelVars)
        tmp = table;
        tmp.animalID = W.animalID;
        tmp.model = repmat(modelLabels(iModel), height(W), 1);
        tmp.modelIndex = repmat(iModel, height(W), 1);
        tmp.deltaLL = W.(modelVars(iModel)) - W.QF;
        plotData = [plotData; tmp]; %#ok<AGROW>
    end

    plotData = outerjoin(plotData, animalSex, 'Keys', 'animalID', ...
        'MergeKeys', true, 'Type', 'left');
    unmatched = ismissing(plotData.sex) | plotData.sex == "";
    if any(unmatched)
        error('Sex missing for animal(s): %s', ...
            strjoin(string(unique(plotData.animalID(unmatched))), ', '));
    end
    if any(~ismember(plotData.sex, ["m","f"]))
        error('Animal sex labels must be m or f.');
    end

    comparison = [
        "GLM split vs single"
        "RL-GLM vs GLM split"
        "2-state RL-GLM-HMM vs RL-GLM"
        "3-state vs 2-state RL-GLM-HMM"
    ];
    modelA = modelVars([2 3 4 5]);
    modelB = modelVars([1 2 3 4]);

    nTests = numel(comparison);
    medianDelta = nan(nTests,1);
    Wstat = nan(nTests,1);
    nPairs = nan(nTests,1);
    nRanked = nan(nTests,1);
    p = nan(nTests,1);
    figureLabel = strings(nTests,1);
    for iTest = 1:nTests
        [p(iTest), Wstat(iTest), nPairs(iTest), nRanked(iTest), ...
            medianDelta(iTest)] = pairedSignrank( ...
            W.(modelA(iTest)), W.(modelB(iTest)));
        figureLabel(iTest) = formatSubmittedPValue(p(iTest));
    end

    statsTable = table(comparison, modelA, modelB, medianDelta, Wstat, ...
        nPairs, nRanked, p, figureLabel, 'VariableNames', { ...
        'comparison','model_A','model_B','median_delta_LL_per_trial', ...
        'W','N_pairs','N_ranked','p','figure_label'});

    plotOrder = flip(modelLabels);
    plotData.plotIndex = nan(height(plotData),1);
    for iModel = 1:numel(plotOrder)
        plotData.plotIndex(plotData.model == plotOrder(iModel)) = iModel;
    end

    fig = figure('Color','w', 'Name','Figure S15C: model comparison', ...
        'Position',[300 200 760 500]);
    ax = axes(fig);
    hold(ax,'on');

    boxplot(ax, plotData.deltaLL, plotData.plotIndex, ...
        'Orientation','horizontal', 'Symbol','', ...
        'Colors',[0.10 0.10 0.10], 'Widths',0.55);
    boxHandles = findobj(ax, 'Tag','Box');
    for k = 1:numel(boxHandles)
        patch(ax, get(boxHandles(k),'XData'), get(boxHandles(k),'YData'), ...
            [0.30 0.55 0.80], 'FaceAlpha',0.60, 'EdgeColor','none', ...
            'HandleVisibility','off');
    end
    boxplot(ax, plotData.deltaLL, plotData.plotIndex, ...
        'Orientation','horizontal', 'Symbol','', ...
        'Colors',[0.10 0.10 0.10], 'Widths',0.55);

    oldRng = rng;
    restoreRng = onCleanup(@() rng(oldRng)); %#ok<NASGU>
    rng(1);
    sexColors = struct('m',[0.20 0.45 0.85], 'f',[0.90 0.35 0.60]);
    for iModel = 1:numel(plotOrder)
        tmp = plotData(plotData.plotIndex == iModel,:);
        y = iModel + (rand(height(tmp),1) - 0.5) .* 0.24;
        for sex = ["m","f"]
            keep = tmp.sex == sex;
            scatter(ax, tmp.deltaLL(keep), y(keep), 34, ...
                sexColors.(char(sex)), 'filled', 'MarkerFaceAlpha',0.28, ...
                'MarkerEdgeColor','none', 'HandleVisibility','off');
        end
    end

    xline(ax, 0, ':', 'Color',[0.20 0.20 0.20], ...
        'LineWidth',1.5, 'HandleVisibility','off');
    set(ax, 'YDir','reverse', 'YTick',1:numel(plotOrder), ...
        'YTickLabel',cellstr(plotOrder), 'TickLabelInterpreter','tex');
    xlabel(ax, '\Delta held-out LL / trial relative to QF');
    title(ax, 'Model comparison');
    xlim(ax,[-0.05 0.18]); ylim(ax,[0.5 5.5]);
    styleAxes(ax);

    topToBottomTest = flip(1:nTests);
    for row = 1:nTests
        test = topToBottomTest(row);
        if p(test) < 0.05
            weight = 'bold';
        else
            weight = 'normal';
        end
        text(ax, 0.155, row + 0.5, figureLabel(test), ...
            'Interpreter','tex', 'FontSize',10, 'FontWeight',weight, ...
            'HorizontalAlignment','left', 'VerticalAlignment','middle');
    end
end


function [fig, sessionTable] = plotExampleSessions(T, sessionTable, colors)
    fig = figure('Color','w', 'Name','Figure S15D-I: example sessions', ...
        'Position',[100 100 1000 1000]);
    layout = tiledlayout(fig, 3, 2, ...
        'TileSpacing','compact', 'Padding','compact');

    observedTrials = nan(height(sessionTable),1);
    firstJOrig = nan(height(sessionTable),1);
    lastJOrig = nan(height(sessionTable),1);

    for iExample = 1:height(sessionTable)
        idx = T.animalID == sessionTable.animalID(iExample) & ...
            T.iOrig == sessionTable.iOrig(iExample);
        S = sortrows(T(idx,:), 'jOrig');
        if isempty(S)
            error('Example %d (animal %d, session %d) was not found.', ...
                sessionTable.example(iExample), ...
                sessionTable.animalID(iExample), ...
                sessionTable.iOrig(iExample));
        end

        observedTrials(iExample) = height(S);
        firstJOrig(iExample) = S.jOrig(1);
        lastJOrig(iExample) = S.jOrig(end);
        if observedTrials(iExample) ~= sessionTable.expected_trials(iExample)
            error(['Example %d has %d trials, but the submitted figure ' ...
                'used %d. Check the posterior input.'], ...
                iExample, observedTrials(iExample), ...
                sessionTable.expected_trials(iExample));
        end

        ax = nexttile(layout);
        hold(ax,'on');
        x = (1:height(S))';
        for state = 1:3
            plot(ax, x, S.(sprintf('stateProb_%d',state)), '-', ...
                'Color',colors(state,:), 'LineWidth',1.5, ...
                'DisplayName',sprintf('State %d',state));
        end
        xlim(ax,[1 height(S)]); ylim(ax,[0 1]);
        xlabel(ax,'Trial'); ylabel(ax,'State probability');
        title(ax,sprintf('Example Session %d',iExample));
        styleAxes(ax);
        if iExample == 2
            legend(ax,'Location','northoutside','Orientation','horizontal', ...
                'Box','off');
        end
    end

    sessionTable.observed_trials = observedTrials;
    sessionTable.first_jOrig = firstJOrig;
    sessionTable.last_jOrig = lastJOrig;
end


function [populationMean, byAnimal] = calculateStateDurations(T, states)
    state = T.stateMAP;
    animal = T.animalID;
    session = T.iOrig;
    isNewRun = [true; ...
        state(2:end) ~= state(1:end-1) | ...
        animal(2:end) ~= animal(1:end-1) | ...
        session(2:end) ~= session(1:end-1)];
    runID = cumsum(isNewRun);

    runState = splitapply(@(x) x(1), state, runID);
    runAnimal = splitapply(@(x) x(1), animal, runID);
    runLength = splitapply(@numel, state, runID);

    animalIDs = unique(animal);
    values = nan(numel(animalIDs), numel(states));
    for iAnimal = 1:numel(animalIDs)
        for iState = 1:numel(states)
            idx = runAnimal == animalIDs(iAnimal) & ...
                runState == states(iState);
            if any(idx)
                values(iAnimal,iState) = mean(runLength(idx), 'omitnan');
            end
        end
    end
    populationMean = mean(values,1,'omitnan');
    byAnimal = array2table(values, ...
        'VariableNames',compose('state_%d',states));
    byAnimal.animalID = animalIDs;
    byAnimal = movevars(byAnimal,'animalID','Before',1);
end


function fig = plotStateDuration(byAnimal, populationMean, colors)
    values = byAnimal{:, {'state_1','state_2','state_3'}};
    fig = figure('Color','w', 'Name','Figure S15J: state duration');
    ax = axes(fig);
    hold(ax,'on');
    bars = bar(ax,1:3,populationMean,0.75, 'FaceColor','flat', ...
        'EdgeColor','none', 'FaceAlpha',0.50);
    bars.CData = colors;
    for iAnimal = 1:size(values,1)
        plot(ax,1:3,values(iAnimal,:),'-', 'Color',[0.78 0.78 0.78], ...
            'LineWidth',0.75, 'HandleVisibility','off');
    end
    for state = 1:3
        valid = isfinite(values(:,state));
        scatter(ax,repmat(state,sum(valid),1),values(valid,state),30, ...
            colors(state,:),'filled','MarkerFaceAlpha',0.30, ...
            'MarkerEdgeColor','none');
    end
    xticks(ax,1:3); xticklabels(ax,compose('State %d',1:3));
    ylabel(ax,'Mean state duration (trials)');
    xlim(ax,[0.5 3.5]); ylim(ax,[0 150]);
    styleAxes(ax);
end


function [sessionTable, byAnimal] = calculateStatesPerSession(T, states)
    sessionTable = unique(T(:, {'animalID','iOrig'}), 'rows');
    sessionTable.nStates = nan(height(sessionTable),1);
    for row = 1:height(sessionTable)
        idx = T.animalID == sessionTable.animalID(row) & ...
            T.iOrig == sessionTable.iOrig(row);
        sessionStates = T.stateMAP(idx);
        sessionStates = sessionStates(isfinite(sessionStates));
        if ~isempty(sessionStates)
            sessionTable.nStates(row) = numel(unique(sessionStates));
        end
    end
    sessionTable = sessionTable(isfinite(sessionTable.nStates),:);

    animalIDs = unique(T.animalID);
    percentages = nan(numel(animalIDs),numel(states));
    nSessions = nan(numel(animalIDs),1);
    for iAnimal = 1:numel(animalIDs)
        counts = sessionTable.nStates( ...
            sessionTable.animalID == animalIDs(iAnimal));
        nSessions(iAnimal) = numel(counts);
        for n = 1:numel(states)
            percentages(iAnimal,n) = 100 .* mean(counts == n);
        end
    end

    byAnimal = array2table(percentages, ...
        'VariableNames',compose('pct_%d_states',states));
    byAnimal.animalID = animalIDs;
    byAnimal.nSessions = nSessions;
    byAnimal = movevars(byAnimal,{'animalID','nSessions'},'Before',1);
end


function fig = plotStatesPerSession(byAnimal, populationMean)
    values = byAnimal{:, {'pct_1_states','pct_2_states','pct_3_states'}};
    fig = figure('Color','w', 'Name','Figure S15K: states per session');
    ax = axes(fig);
    hold(ax,'on');
    bar(ax,1:3,populationMean,0.75, 'FaceColor',[0.55 0.55 0.55], ...
        'EdgeColor','none','FaceAlpha',0.60);
    for iAnimal = 1:size(values,1)
        plot(ax,1:3,values(iAnimal,:),'-', 'Color',[0.72 0.72 0.72], ...
            'LineWidth',0.75, 'HandleVisibility','off');
        scatter(ax,1:3,values(iAnimal,:),28,[0 0 0],'filled', ...
            'MarkerFaceAlpha',0.35,'MarkerEdgeColor','none', ...
            'HandleVisibility','off');
    end
    xlabel(ax,'n(States per session)'); ylabel(ax,'Sessions (%)');
    xticks(ax,1:3); xlim(ax,[0.5 3.5]); ylim(ax,[0 100]);
    styleAxes(ax);
end


function [counts, probabilities] = calculateEmpiricalTransitions(T, states)
    sameSession = ...
        T.animalID(2:end) == T.animalID(1:end-1) & ...
        T.iOrig(2:end) == T.iOrig(1:end-1);
    from = T.stateMAP(1:end-1);
    to = T.stateMAP(2:end);
    from = from(sameSession);
    to = to(sameSession);
    [~,fromIndex] = ismember(from,states);
    [~,toIndex] = ismember(to,states);
    counts = accumarray([fromIndex,toIndex],1,[numel(states),numel(states)]);

    offDiagonalCounts = counts;
    offDiagonalCounts(1:numel(states)+1:end) = 0;
    rowTotals = sum(offDiagonalCounts,2);
    if any(rowTotals == 0)
        error('At least one state has no observed off-diagonal transitions.');
    end
    probabilities = offDiagonalCounts ./ rowTotals;
end


function fig = plotEmpiricalTransitions(probabilities)
    displayMatrix = probabilities;
    displayMatrix(1:4:end) = NaN;
    fig = figure('Color','w', 'Name','Figure S15L: empirical transitions');
    ax = axes(fig);
    imageHandle = imagesc(ax,displayMatrix,[0 1]);
    imageHandle.AlphaData = isfinite(displayMatrix);
    ax.Color = [0.65 0.65 0.65];
    axis(ax,'square');
    colormap(ax,parula(256));
    cb = colorbar(ax);
    cb.Label.String = 'Row-normalized p(transition)';
    xlabel(ax,'To state'); ylabel(ax,'From state');
    xticks(ax,1:3); yticks(ax,1:3);
    xticklabels(ax,string(1:3)); yticklabels(ax,string(1:3));
    styleAxes(ax);
end


function statsTable = compareStatesToOne( ...
        values, states, comparisons, deltaVariableName)
    nTests = size(comparisons,1);
    comparison = strings(nTests,1);
    medianDelta = nan(nTests,1);
    W = nan(nTests,1);
    nPairs = nan(nTests,1);
    nRanked = nan(nTests,1);
    pRaw = nan(nTests,1);
    for iTest = 1:nTests
        stateA = comparisons(iTest,1);
        stateB = comparisons(iTest,2);
        [pRaw(iTest),W(iTest),nPairs(iTest),nRanked(iTest), ...
            medianDelta(iTest)] = pairedSignrank( ...
            values(:,states == stateA), values(:,states == stateB));
        comparison(iTest) = sprintf('State %d vs State %d',stateA,stateB);
    end
    pHolm = holmAdjust(pRaw);
    statsTable = table(comparison,medianDelta,W,nPairs,nRanked,pRaw,pHolm, ...
        'VariableNames',{'comparison',deltaVariableName,'W', ...
        'N_pairs','N_ranked','p_raw','p_Holm'});
end


function [p,W,nPairs,nRanked,medianDelta] = pairedSignrank(a,b)
    keep = isfinite(a) & isfinite(b);
    a = a(keep);
    b = b(keep);
    delta = a - b;
    nPairs = numel(delta);
    nRanked = sum(delta ~= 0);
    medianDelta = median(delta,'omitnan');
    p = NaN;
    W = NaN;
    if nRanked > 0
        [p,~,signedRankStats] = signrank(a,b);
        W = signedRankStats.signedrank;
    end
end


function pAdjusted = holmAdjust(pRaw)
    pAdjusted = nan(size(pRaw));
    validIndices = find(isfinite(pRaw));
    if isempty(validIndices)
        return;
    end
    [pSorted,order] = sort(pRaw(validIndices));
    m = numel(pSorted);
    adjustedSorted = (m - (1:m)' + 1) .* pSorted(:);
    adjustedSorted = min(cummax(adjustedSorted),1);
    pAdjusted(validIndices(order)) = adjustedSorted;
end


function label = formatSubmittedPValue(p)
    if ~isfinite(p)
        label = "p = n.a.";
    elseif p < 1e-6
        label = "p < 10^{-6}*";
    elseif p < 1e-4
        label = "p < 10^{-4}*";
    elseif p < 0.05
        label = "p = " + string(sprintf('%.2f',p)) + "*";
    else
        label = "p = " + string(sprintf('%.2f',p));
    end
end


function tableOut = matrixToStateTable(matrix,states)
    tableOut = array2table(matrix, ...
        'VariableNames',compose('to_state_%d',states));
    tableOut.from_state = states;
    tableOut = movevars(tableOut,'from_state','Before',1);
end


function requireVariables(T,required,description)
    missing = setdiff(required,T.Properties.VariableNames,'stable');
    if ~isempty(missing)
        error('%s missing required variables: %s', ...
            description,strjoin(missing,', '));
    end
end


function assertUniqueRows(T,keys,description)
    [~,uniqueRows] = unique(T(:,keys),'rows','stable');
    if numel(uniqueRows) ~= height(T)
        error('%s contains duplicate key rows.',description);
    end
end


function styleAxes(ax)
    set(ax,'Box','off','TickDir','out','FontSize',11,'LineWidth',1.1);
end


function saveFigurePair(fig,outputFolder,baseName)
    exportgraphics(fig,fullfile(outputFolder,[baseName '.png']), ...
        'Resolution',300);
    exportgraphics(fig,fullfile(outputFolder,[baseName '.pdf']), ...
        'ContentType','vector');
end


function writeResultTable(T,outputFolder,filename)
    writetable(T,fullfile(outputFolder,filename));
end
